# Site
name: 'Edit Arşiv'
language: "tr"
description: 'Videolarınızın ihtiyacı olan kesitler... '
url: 'https://editarsiv.com'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon/favicon.ico'
baseurl: ''



# Social Settings
disqus: #'demowebsite'
email: 'videoarsiv@nexusvis.com'
mailchimp-list: #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
#twitter: ''
#facebook: ''
instagram: ''
linkedin: ''
#youtube: ''
#telegram: ''

pagepreview:
  enabled: false
  prefix: ''
  postfix: ''

include: ["_pages"]
permalink: /:title/



# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-gist
 



# Syntax
markdown: kramdown
highlighter: rouge

# XML feed
feed:
  collections:
    - videos
    - companys
    - catalogs
    - illustrators
    - newsletter
  excerpt_only: true  # Sadece özet içeriği kullan
  disable_in_development: true  # Geliştirme ortamında devre dışı bırak

# excerpt
excerpt_separator: <!--more-->

# Paginate
paginate: 10
#paginate_path: /page:num/
paginate_path: "/blog/page:num/"

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

collections:
  books:
    output: true
    permalink: /titles/:title
  videos:
    output: true
    permalink: /videos/:title
  
plugins:
  - jekyll-sitemap
# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

#incremental: true
